sudo: false
language: ruby
rvm:
  - ruby-2.2.2

cache:
  - bundler

addons:
  postgresql: 9.3

services:
  - redis
  - postgres

before_script:
  - 'cp config/database.yml.example config/database.yml'
  - 'cp config/travis.yml.example config/travis.yml'
  - 'psql -c "create database travis_logs;" -U postgres'
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

script:
  - bundle exec rspec
